---
apiVersion: v1
kind: Service
metadata:
  name: quarantine-webhook
  namespace: dev
spec:
  selector:
    app: incident-operator
    component: incident-validation-webhook
  ports:
  - name: webhook
    port: 443
    targetPort: 9443
