{{- range $client := .Values.clients }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $client.name }}
  namespace: {{ $client.namespace }}
  annotations:
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "10"
data:
  pw: {{ randAlphaNum 8 | b64enc  | quote }}
type: Opaque
{{- end }}
