apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "testing-dep.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "testing-dep.name" . }}
    helm.sh/chart: {{ template "testing-dep.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  {{- if .Values.podPriorityClassName }}
  pod_priority_class_name: {{ .Values.podPriorityClassName }}
  {{- end }}
  key1: value1
  key2: value2
