---
apiVersion: batch/v1
kind: Job
metadata:
  name: create-webhook-config
  annotations:
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "10"
spec:
  template:
    spec:
      serviceAccountName: incident-operator-webhook-create
      containers:
      - name: create-webhook-config
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        args:
        - "webhook"
        - "certs"
      restartPolicy: Never
  backoffLimit: 3
