---
apiVersion: batch/v1
kind: Job
metadata:
  name: delete-webhook-config
  annotations:
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook": "pre-delete"
spec:
  template:
    spec:
      serviceAccountName: incident-operator-webhook-delete
      containers:
      - name: delete-webhook-config
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        args:
        - "webhook"
        - "delete"
        - "--namespace"
        - "{{ .Release.Namespace }}"
      restartPolicy: Never
  backoffLimit: 3
