---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: incident-controller-manager
  labels:
    app: incident-operator
    component: incident-controller-manager
spec:
  selector:
    matchLabels:
      app: incident-operator
      component: incident-controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        app: incident-operator
        component: incident-controller-manager
    spec:
      serviceAccountName: incident-operator
      securityContext:
        runAsUser: 65532
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: incident-manager
        args:
        - "operator"
        - "serve"
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: "{{ .Values.operator.resources.limits.cpu }}"
            memory: "{{ .Values.operator.resources.limits.memory }}"
          requests:
            cpu: "{{ .Values.operator.resources.requests.cpu }}"
            memory: "{{ .Values.operator.resources.requests.memory }}"
      terminationGracePeriodSeconds: 10
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: ops.soer3n.info/isolate
                operator: DoesNotExist
