---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: incident-operator

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: incident-operator-webhook
  annotations:
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook": "pre-delete,post-delete,post-install"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: incident-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: incident-operator-role
subjects:
- kind: ServiceAccount
  name: incident-operator
  namespace: "{{ .Release.Namespace }}"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: incident-operator-webhook-rolebinding
  annotations:
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook": "pre-delete,post-delete,post-install"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: incident-operator-webhook-role
subjects:
- kind: ServiceAccount
  name: incident-operator-webhook

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: incident-operator-role
rules:
- apiGroups:
  - ''
  resources:
  - 'pods'
  verbs:
  - 'update'
  - 'patch'
  - 'create'
  - 'delete'
  - 'get'
  - 'list'
  - 'watch'
- apiGroups:
  - ''
  resources:
  - 'nodes'
  verbs:
  - 'update'
  - 'patch'
  - 'get'
  - 'list'
  - 'watch'
- apiGroups:
  - 'apps'
  resources:
  - 'deployments'
  - 'daemonsets'
  verbs:
  - 'update'
  - 'patch'
  - 'get'
  - 'list'
  - 'watch'
- apiGroups:
  - 'ops.soer3n.info'
  resources:
  - 'quarantines'
  - 'quarantines/status'
  verbs:
  - 'update'
  - 'patch'
  - 'get'
  - 'list'
  - 'watch'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: incident-operator-webhook-role
  annotations:
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook": "pre-delete,post-delete,post-install"
rules:
- apiGroups:
  - ''
  resources:
  - 'pods'
  - 'secrets'
  verbs:
  - 'update'
  - 'patch'
  - 'create'
  - 'delete'
  - 'get'
  - 'list'
  - 'watch'
- apiGroups:
  - 'admissionregistration.k8s.io'
  resources:
  - 'validatingwebhookconfigurations'
  verbs:
  - 'update'
  - 'create'
  - 'get'
