---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: incident-operator

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: incident-operator-webhook

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: incident-operator-webhook-create
  annotations:
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "0"

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: incident-operator-webhook-delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: incident-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: incident-operator-role
subjects:
- kind: ServiceAccount
  name: incident-operator
  namespace: "{{ .Release.Namespace }}"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: incident-operator-webhook-create-rolebinding
  annotations:
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "0"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: incident-operator-webhook-create-role
subjects:
- kind: ServiceAccount
  name: incident-operator-webhook-create
  namespace: "{{ .Release.Namespace }}"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: incident-operator-webhook-delete-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: incident-operator-webhook-delete-role
subjects:
- kind: ServiceAccount
  name: incident-operator-webhook-delete
  namespace: "{{ .Release.Namespace }}"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: incident-operator-webhook-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: incident-operator-webhook-role
subjects:
- kind: ServiceAccount
  name: incident-operator-webhook
  namespace: "{{ .Release.Namespace }}"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: incident-operator-role
rules:
- apiGroups:
  - ''
  resources:
  - 'pods'
  - 'pods/eviction'
  - 'events'
  verbs:
  - 'update'
  - 'patch'
  - 'create'
  - 'delete'
  - 'get'
  - 'list'
  - 'watch'
- apiGroups:
  - ''
  resources:
  - 'nodes'
  verbs:
  - 'update'
  - 'patch'
  - 'get'
  - 'list'
  - 'watch'
- apiGroups:
  - 'apps'
  resources:
  - 'deployments'
  - 'daemonsets'
  verbs:
  - 'update'
  - 'patch'
  - 'get'
  - 'list'
  - 'watch'
- apiGroups:
  - 'ops.soer3n.info'
  resources:
  - 'quarantines'
  - 'quarantines/status'
  verbs:
  - 'update'
  - 'patch'
  - 'get'
  - 'list'
  - 'watch'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: incident-operator-webhook-create-role
  annotations:
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "0"
rules:
- apiGroups:
  - ''
  resources:
  - 'secrets'
  verbs:
  - 'update'
  - 'create'
  - 'get'
  - 'watch'
- apiGroups:
  - 'admissionregistration.k8s.io'
  resources:
  - 'validatingwebhookconfigurations'
  - 'mutatingwebhookconfigurations'
  verbs:
  - 'update'
  - 'create'
  - 'get'
  - 'watch'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: incident-operator-webhook-delete-role
rules:
- apiGroups:
  - ''
  resources:
  - 'secrets'
  verbs:
  - 'delete'
  - 'get'
  - 'watch'
  - 'list'
- apiGroups:
  - 'admissionregistration.k8s.io'
  resources:
  - 'validatingwebhookconfigurations'
  - 'mutatingwebhookconfigurations'
  verbs:
  - 'delete'
  - 'get'
  - 'watch'
  - 'list'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: incident-operator-webhook-role
rules:
- apiGroups:
  - ''
  resources:
  - 'pods'
  verbs:
  - 'update'
  - 'patch'
  - 'create'
  - 'delete'
  - 'get'
  - 'list'
  - 'watch'
