---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: incident-validation-webhook
  labels:
    app: incident-operator
    component: incident-validation-webhook
spec:
  selector:
    matchLabels:
      app: incident-operator
      component: incident-validation-webhook
  replicas: 1
  template:
    metadata:
      labels:
        app: incident-operator
        component: incident-validation-webhook
    spec:
      serviceAccountName: incident-operator-webhook
      securityContext:
        runAsUser: 65532
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: validation-webhook
        args:
          - "webhook"
          - "serve"
          - "--cert-dir"
          - "{{ .Values.webhook.certDir }}"
        securityContext:
          allowPrivilegeEscalation: false
        resources:
          limits:
            cpu: "{{ .Values.webhook.resources.limits.cpu }}"
            memory: "{{ .Values.webhook.resources.limits.memory }}"
          requests:
            cpu: "{{ .Values.webhook.resources.requests.cpu }}"
            memory: "{{ .Values.webhook.resources.requests.memory }}"
        volumeMounts:
          - mountPath: "{{ .Values.webhook.certDir }}"
            name: webhook-tls
            readOnly: true
      terminationGracePeriodSeconds: 10
      volumes:
        - name: webhook-tls
          secret:
            secretName: incident-webhook
