---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.webhook.service.name }}"
spec:
  selector:
    app: incident-operator
    component: incident-validation-webhook
  ports:
  - name: webhook
    port: {{ .Values.webhook.service.port }}
    targetPort: 9443
