image:
  repository: ghcr.io/soer3n/incident-operator
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v0.1.1"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

operator:
  resources:
    limits:
      cpu: 100m
      memory: 300Mi
    requests:
      cpu: 100m
      memory: 200Mi

webhook:
  service:
    type: ClusterIP
    port: 443
    name: quarantine-webhook
  resources:
    limits:
      cpu: 100m
      memory: 300Mi
    requests:
      cpu: 100m
      memory: 200Mi

nodeSelector: {}

tolerations: []

affinity: {}
