certmanager:
  apiVersion: cert-manager.io/v1

issuer:
- name: mtls-issuer
  namespace: cert-manager
  duration: 2880h # 120d
  renewBefore: 360h # 15d
  commonName: mtls-ca

###############################
# example:
#
# servers:
# - name: example-server
#   namespace: cert-manager
#   issuer: mtls-issuer
#   duration: 2160h # 90d
#   renewBefore: 360h # 15d
#   privateKey:
#     algorithm: RSA
#     encoding: PKCS1
#     size: 2048
#   commonName: ExampleServer
################################
servers: []

###############################
# example:
#
# clients:
# - name: example-client
#   namespace: cert-manager
#   issuer: mtls-issuer
#   duration: 2160h # 90d
#   renewBefore: 360h # 15d
#   privateKey:
#     algorithm: RSA
#     encoding: PKCS1
#     size: 2048
#   commonName: ExampleClient
#   keystores:
#     pkcs12:
#       create: true
################################
clients: []
