name: Lint and Test Charts

on:
  push:
    branches: [ gh-pages ]
  pull_request:
    paths:
      - 'testing/testing_a/**'

jobs:
  lint-chart:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install python env
        run: sudo apt-get update && sudo apt-get install -y python3.8-venv
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.1.0
      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi
      - name: Run chart-testing (lint)
        run: ct lint

  install-chart:
    name: install-chart
    runs-on: self-hosted
    needs:
      - lint-chart
    strategy:
      matrix:
        k8s:
          - v1.21.1
          - v1.20.7
          - v1.19.11
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Create kind ${{ matrix.k8s }} cluster
        uses: helm/kind-action@main
        with:
          node_image: kindest/node:${{ matrix.k8s }}
      - name: Install python env
        run: sudo apt-get update && sudo apt-get install -y python3.8-venv
      - name: Run chart-testing (install)
        uses: helm/chart-testing-action@v2.1.0
      - name: Run chart-testing (install)
        run: ct install
