name: Lint and Test Charts

on:
  pull_request:
    paths:
      - 'testing/testing_a/**'

jobs:
  lint-chart:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run chart-testing (lint)
        uses: helm/chart-testing-action@main
        with:
          command: lint
          config: .github/ct.yaml

  install-chart:
    name: install-chart
    runs-on: self-hosted
    needs:
      - lint-chart
    strategy:
      matrix:
        k8s:
          - v1.21.1
          - v1.20.7
          - v1.19.11
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Create kind ${{ matrix.k8s }} cluster
        uses: helm/kind-action@main
        with:
          node_image: kindest/node:${{ matrix.k8s }}
      - name: Run chart-testing (install)
        uses: helm/chart-testing-action@main
        with:
          command: install
          config: .github/ct.yaml
