name: release
on: 
  push:
    branches:
      - master
    paths:
      - 'stable/**'
  release:
    types: [published, created]

jobs:
  testing_a:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publish Helm charts
        uses: stefanprodan/helm-gh-pages@v1.4.1
        with:
          token: ${{ secrets.CR_TOKEN }}
          charts_dir: stable
  testing_b:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publish Helm charts
        uses: stefanprodan/helm-gh-pages@v1.4.1
        with:
          token: ${{ secrets.CR_TOKEN }}
          charts_dir: stable
